# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f1af17ba0d8c007de272a8f205f453abf71e25a57994718466ab0e956264395b8179c0ca0875372846e119514e7a75e7f887a1292e2abe046b0e1c9e3e857e1

test:
  secret_key_base: 51d36489946dbdb7ad16a1174988a3eed7184ff8d9691fcacf34dc1650e22fc697932d072cdc0e4d1acb0a0cc90577d5c7facdd2f54120ea2cb2d378fa2ef609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
